name: Client Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Ensure Python Runtime
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Ensure PDM & twine
        run: |
          python3 -m pip install pdm pdm-mina mina-build

      - name: Build Package
        run: |
          export MINA_BUILD_TARGET=client && pdm mina build client

      - name: Publish Package
        run: |
          pdm publish --no-build
          gh release upload --clobber ${{ inputs.version }} dist/*.tar.gz dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
