name: Client Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - client-v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Ensure Python Runtime
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Ensure PDM & twine
        run: |
          python3 -m pip install pdm pdm-mina mina-build

      - name: Get Version
        id: version
        run: |
          echo "VERSION=$(pdm show --version)" >> $GITHUB_OUTPUT
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/client-v}" >> $GITHUB_OUTPUT
          echo "TAG_NAME=${GITHUB_REF#refs/tags/client-}" >> $GITHUB_OUTPUT

      - name: Check Version
        if: steps.version.outputs.VERSION != steps.version.outputs.TAG_VERSION
        run: exit 1

      - name: Build Package
        run: |
          pdm mina build client

      - name: Publish Package
        run: |
          pdm publish --no-build
          gh release upload --clobber ${{ steps.version.outputs.TAG_NAME }} dist/*.tar.gz dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
