name: Full Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Get Version
        id: version
        run: |
          echo "VERSION=$(pdm show --version -q)" >> $GITHUB_OUTPUT
          if [[ "${{ github.event_name }}" == 'push' ]]; then
            echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            input_version=${{ github.event.inputs.version }}
            echo "TAG_VERSION=${input_version#v}" >> $GITHUB_OUTPUT
            echo "TAG_NAME=${input_version}" >> $GITHUB_OUTPUT
          fi

      - name: Check Version
        if: steps.version.outputs.VERSION != steps.version.outputs.TAG_VERSION
        run: exit 1

      - name: Build Package
        run: |
          pdm build

      - name: Publish Package
        run: |
          pdm publish --no-build
          gh release upload --clobber ${{ steps.version.outputs.TAG_NAME }} dist/*.tar.gz dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
